---
volumes:
  pihole-ftl: {}

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:${PIHOLE_VERSION}
    restart: unless-stopped
    hostname: locke
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 80:80/tcp
      - 443:443/tcp
    environment:
      - ServerIP=192.168.1.198
      - TZ=Australia/Melbourne
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
      - pihole-ftl:/etc/ftldb
    env_file:
      - .secrets
