---
volumes:
  pihole-ftl:
    labels:
      net.mafro.kopia: true

networks:
  caddy:
    external: true

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:${PIHOLE_VERSION}
    restart: unless-stopped
    hostname: locke
    # https://github.com/pi-hole/docker-pi-hole#note-on-capabilities
    cap_add:
      - NET_ADMIN
    networks:
      - default
      - caddy
    ports:
      - 53:53/tcp
      - 53:53/udp
    environment:
      - FTLCONF_LOCAL_IPV4=192.168.1.198
      - TZ=Australia/Melbourne
      - DNS1=1.1.1.1
      - DNS2=1.0.0.1
    volumes:
      - ./etc-pihole/:/etc/pihole/
      - ./etc-dnsmasq.d/:/etc/dnsmasq.d/
      - pihole-ftl:/etc/ftldb
    env_file:
      - .secrets
    labels:
      caddy: pihole.mafro.net
      caddy.tls.ca: https://ca.mafro.net:4433/acme/acme/directory
      caddy.tls.ca_root: /root/step_ca.crt
      caddy.reverse_proxy: "{{upstreams 80}}"
